---

- hosts: all
  become: true
  tasks:

    - name: Update and upgrade apt packages
      apt:
        update-cache: yes
        state: latest
        upgrade: dist
        
    - name: Install required software
      apt:
        name:
          - software-properties-common
          - mesa-utils
      when: ansible_distribution in ["Debian", "Ubuntu"]

#    - name: add mesa repo
#      apt_repository:
#        repo: ppa:kisak/kisak-mesa    

#    - name: apt update
#      apt:
#        update-cache: true
