---

- hosts: all
  become: true
  tasks:

#    - name: apt update
#      apt:
#        update-cache: true
# moved down in the same operation
        
    - name: add graphics packages and utils
      apt:
        name:
          - software-properties-common
          - mesa-utils
      update-cache: true
      when: ansible_distribution in ["Debian", "Ubuntu"]

#    - name: add mesa repo
#      apt_repository:
#        repo: ppa:kisak/kisak-mesa    

#    - name: apt update
#      apt:
#        update-cache: true
